### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alebondarenko** [webis-de/targer#2]
- [ ] Move deployments to the new ES
- [ ] API: change the models names
- [ ] API: add the search arguments endpoint
- [ ] Document deployment instructions

**Comment by heinrichreimer** [comment]
Moved discussion to separate issues #3, #4, #5, #6.
